spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/oauth?characterEncoding=utf8&serverTimezone=Hongkong&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 1
      maximum-pool-size: 3
      idle-timeout: 10000
      max-lifetime: 1800000
      connection-timeout: 500
      login-timeout: 500
      validation-timeout: 1000
      initialization-fail-timeout: 1000
      connection-test-query: select 1


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.security.securityframework.beans.po
  global-config:
    db-config:
      id-type: assign_id


logging:
  level:
    com.generator.dao: DEBUG


wei:
    jwt:
      iss: wei
      sub: token
      aud: wei
      expireDate: 999999
      startDate: 0